A toolkit for parsing and rendering Org-mode.

* Features

- [X] org-mode parser implement using Rust
- [-] SSG(static site generator) from org files, which supports anonymous discusstion.
- [ ] org-roam


* Usage

** How to use?

#+begin_src bash
  # cargo install windancer
  cargo build -r
  cargo run --bin winacer
  windancer --help
#+end_src

see [[file:docs/status.org][status]] for status.


** input

A directory containing all the resources, such as org files, images in the org files, see [[file:examples/mysite/note/][note]] in example.


* Development

#+begin_src bash
  cargo test

  # bench
  cargo bench
  # performance
  cargo flamegraph --example main
  perf report
#+end_src


** Planning
- doc
- windancer usage of ssg
- keyword: multple parser, search k2v, keyword
- support config of subscript
- Error: Rich maybe slow
- use group rather then nested then?
- image width: max?
- link: roam node id?
- #+include keyword to include files in compile stage
  

** misc

*** about index.html

index.html is recogized if filename is the same to parent directory.


*** PRE during parsing

https://github.com/zesterer/chumsky/issues/943

- get byte index of previous utf8 char from input, rather than using state.
- require chumsky's have public APT to visit the raw_input, such as InputRef::full_slice() be public.


** change log


- 2026-01-15 13:42:49: Support parse/render from input directory to output directory
- 2026-01-05 20:12:45: Remove Rollback state, using ctx and *inp.full_slice()* to visit PRE(previous char), parse speed is 2x (for test file: 50ms -> 26ms). Note since chumsky full_slice() API is not public, so only local version chumsky worked. See [[https://github.com/zesterer/chumsky/issues/943][chumsky issue 946]]


** Reference

- [[https://orgmode.org/worg/org-syntax.html][org-syntax]]
- [[https://github.com/zesterer/chumsky][chumsky]]
- [[https://github.com/tfeldmann/organize][orgize]]
- mdbook



* Contribute

You can support my work on [[https://ko-fi.com/cnglen][ko-fi]].

Another way to help is to report issues or suggest new features.


