A toolkit for parsing and rendering org-mode.

* Features

- Single binary
- A parser implemented using Rust
- SSG(static site generator) from a directory, which containing org files
  - anonymous discusstion can be supported by [[https://github.com/cnglen/tinydis][tinydis]]

** Todo

- [ ] org-roam for knowledge
- [ ] search by keyword
- [ ] better documenation
  

* Usage

** Quick start

Build from source:
#+begin_src bash
  git clone https://github.com/cnglen/windancer.git
  cd windancer && cargo build -r

  # example
  cargo run -- -c ./examples/mysite/config.toml
  python -m http.server -d mysite.publish
#+end_src

Download from release page:
#+begin_src bash
  wget https://github.com/cnglen/windancer/releases/download/v0.2.0/windancer-x86_64-unknown-linux-gnu.tar.gz -O /tmp/windancer.tar.gz && tar xvfz /tmp/windancer.tar.gz -C ~/.local/bin/
  windancer -i PATH_OF_DIRECTOY_OF_ORG_FILES -o /tmp/output
#+end_src




** Config

A directory containing all the resources, such as org files, images in the org files, see [[file:examples/mysite/note/][note]] in example.

* FAQ

** Q: Are all org-mode syntax supported?

See [[file:docs/status.org][status]]

** Q: Why implement org-mode parsing in Rust?

Emacs comes with built-in org-mode support, including its own parser. However, customization or exporting to other tools can be cumbersome. Since I’m not familiar with Emacs Lisp, I chose to implement the parsing logic in Rust instead.

There are plenty of SSG tools for Markdown, but native org-mode support is rare. The usual approach is to convert org-mode to Markdown, but that often results in imperfect output.

That’s why windancer is created—to parse org-mode directly and render it as an HTML site. PDF export may be added in the future.


* Contribute

You can support my work on [[https://ko-fi.com/cnglen][ko-fi]].

Another way to help is to report issues or suggest new features.


