use phf::{phf_map, phf_set};

pub(crate) static ENTITYNAME_TO_HTML: phf::Map<&'static str, &'static str> = phf_map! {
        // * letters
        // ** latin
        "Agrave" => "&Agrave;",
        "agrave" => "&agrave;",
        "Aacute" => "&Aacute;",
        "aacute" => "&aacute;",
        "Acirc" => "&Acirc;",
        "acirc" => "&acirc;",
        "Amacr" => "&Amacr;",
        "amacr" => "&amacr;",
        "Atilde" => "&Atilde;",
        "atilde" => "&atilde;",
        "Auml" => "&Auml;",
        "auml" => "&auml;",
        "Aring" => "&Aring;",
        "AA" => "&Aring;",
        "aring" => "&aring;",
        "AElig" => "&AElig;",
        "aelig" => "&aelig;",
        "Ccedil" => "&Ccedil;",
        "ccedil" => "&ccedil;",
        "Egrave" => "&Egrave;",
        "egrave" => "&egrave;",
        "Eacute" => "&Eacute;",
        "eacute" => "&eacute;",
        "Ecirc" => "&Ecirc;",
        "ecirc" => "&ecirc;",
        "Euml" => "&Euml;",
        "euml" => "&euml;",
        "Igrave" => "&Igrave;",
        "igrave" => "&igrave;",
        "Iacute" => "&Iacute;",
        "iacute" => "&iacute;",
        "Idot" => "&idot;",
        "inodot" => "&inodot;",
        "Icirc" => "&Icirc;",
        "icirc" => "&icirc;",
        "Iuml" => "&Iuml;",
        "iuml" => "&iuml;",
        "Ntilde" => "&Ntilde;",
        "ntilde" => "&ntilde;",
        "Ograve" => "&Ograve;",
        "ograve" => "&ograve;",
        "Oacute" => "&Oacute;",
        "oacute" => "&oacute;",
        "Ocirc" => "&Ocirc;",
        "ocirc" => "&ocirc;",
        "Otilde" => "&Otilde;",
        "otilde" => "&otilde;",
        "Ouml" => "&Ouml;",
        "ouml" => "&ouml;",
        "Oslash" => "&Oslash;",
        "oslash" => "&oslash;",
        "OElig" => "&OElig;",
        "oelig" => "&oelig;",
        "Scaron" => "&Scaron;",
        "scaron" => "&scaron;",
        "szlig" => "&szlig;",
        "Ugrave" => "&Ugrave;",
        "ugrave" => "&ugrave;",
        "Uacute" => "&Uacute;",
        "uacute" => "&uacute;",
        "Ucirc" => "&Ucirc;",
        "ucirc" => "&ucirc;",
        "Uuml" => "&Uuml;",
        "uuml" => "&uuml;",
        "Yacute" => "&Yacute;",
        "yacute" => "&yacute;",
        "Yuml" => "&Yuml;",
        "yuml" => "&yuml;",

        // ** Latin special face,"
        "fnof" => "&fnof;",
        "real" => "&real;",
        "image" => "&image;",
        "weierp" => "&weierp;",
        "ell" => "&ell;",
        "imath" => "&imath;",
        "jmath" => "&jmath;",

        // ** Greek"
        "Alpha" => "&Alpha;",
        "alpha" => "&alpha;",
        "Beta" => "&Beta;",
        "beta" => "&beta;",
        "Gamma" => "&Gamma;",
        "gamma" => "&gamma;",
        "Delta" => "&Delta;",
        "delta" => "&delta;",
        "Epsilon" => "&Epsilon;",
        "epsilon" => "&epsilon;",
        "varepsilon" => "&epsilon;",
        "Zeta" => "&Zeta;",
        "zeta" => "&zeta;",
        "Eta" => "&Eta;",
        "eta" => "&eta;",
        "Theta" => "&Theta;",
        "theta" => "&theta;",
        "thetasym" => "&thetasym;",
        "vartheta" => "&thetasym;",
        "Iota" => "&Iota;",
        "iota" => "&iota;",
        "Kappa" => "&Kappa;",
        "kappa" => "&kappa;",
        "Lambda" => "&Lambda;",
        "lambda" => "&lambda;",
        "Mu" => "&Mu;",
        "mu" => "&mu;",
        "nu" => "&nu;",
        "Nu" => "&Nu;",
        "Xi" => "&Xi;",
        "xi" => "&xi;",
        "Omicron" => "&Omicron;",
        "omicron" => "&omicron;",
        "Pi" => "&Pi;",
        "pi" => "&pi;",
        "Rho" => "&Rho;",
        "rho" => "&rho;",
        "Sigma" => "&Sigma;",
        "sigma" => "&sigma;",
        "sigmaf" => "&sigmaf;",
        "varsigma" => "&sigmaf;",
        "Tau" => "&Tau;",
        "Upsilon" => "&Upsilon;",
        "upsih" => "&upsih;",
        "upsilon" => "&upsilon;",
        "Phi" => "&Phi;",
        "phi" => "&phi;",
        "varphi" => "&varphi;",
        "Chi" => "&Chi;",
        "chi" => "&chi;",
        "acutex" => "&acute;x",
        "Psi" => "&Psi;",
        "psi" => "&psi;",
        "tau" => "&tau;",
        "Omega" => "&Omega;",
        "omega" => "&omega;",
        "piv" => "&piv;",
        "varpi" => "&piv;",
        "partial" => "&part;",

        // ** Hebrew"
        "alefsym" => "&alefsym;",
        "aleph" => "&aleph;",
        "gimel" => "&gimel;",
        "beth" => "&beth;",
        "dalet" => "&daleth;",

        // ** Icelandic"
        "ETH" => "&ETH;",
        "eth" => "&eth;",
        "THORN" => "&THORN;",
        "thorn" => "&thorn;",

        // * Punctuation"
        // ** Dots and Marks"
        "dots" => "&hellip;",
        "cdots" => "&ctdot;",
        "hellip" => "&hellip;",
        "middot" => "&middot;",
        "iexcl" => "&iexcl;",
        "iquest" => "&iquest;",

        // ** Dash-like"
        "shy" => "&shy;",
        "ndash" => "&ndash;",
        "mdash" => "&mdash;",

        // ** Quotations"
        "quot" => "&quot;",
        "acute" => "&acute;",
        "ldquo" => "&ldquo;",
        "rdquo" => "&rdquo;",
        "bdquo" => "&bdquo;",
        "lsquo" => "&lsquo;",
        "rsquo" => "&rsquo;",
        "sbquo" => "&sbquo;",
        "laquo" => "&laquo;",
        "raquo" => "&raquo;",
        "lsaquo" => "&lsaquo;",
        "rsaquo" => "&rsaquo;",

        // * Other"
        // ** Misc. often used"
        "circ" => "&circ;",
        "vert" => "&vert;",
        "vbar" => "|",
        "brvbar" => "&brvbar;",
        "S" => "&sect;",
        "sect" => "&sect;",
        "P" => "&para;",
        "para" => "&para;",
        "amp" => "&amp;",
        "lt" => "&lt;",
        "gt" => "&gt;",
        "tilde" => "~",
        "slash" => "/",
        "plus" => "+",
        "under" => "_",
        "equal" => "=",
        "asciicirc" => "^",
        "dagger" => "&dagger;",
        "dag" => "&dagger;",
        "Dagger" => "&Dagger;",
        "ddag" => "&Dagger;",

        // ** Whitespace"
        "nbsp" => "&nbsp;",
        "ensp" => "&ensp;",
        "emsp" => "&emsp;",
        "thinsp" => "&thinsp;",

        // ** Currency"
        "curren" => "&curren;",
        "cent" => "&cent;",
        "pound" => "&pound;",
        "yen" => "&yen;",
        "euro" => "&euro;",
        "EUR" => "&euro;",
        "dollar" => "$",
        "USD" => "$",

        // ** Property Marks"
        "copy" => "&copy;",
        "reg" => "&reg;",
        "trade" => "&trade;",

        // ** Science et al."
        "minus" => "&minus;",
        "pm" => "&plusmn;",
        "plusmn" => "&plusmn;",
        "times" => "&times;",
        "frasl" => "&frasl;",
        "colon" => ":",
        "div" => "&divide;",
        "frac12" => "&frac12;",
        "frac14" => "&frac14;",
        "frac34" => "&frac34;",
        "permil" => "&permil;",
        "sup1" => "&sup1;",
        "sup2" => "&sup2;",
        "sup3" => "&sup3;",
        "radic" => "&radic;",
        "sum" => "&sum;",
        "prod" => "&prod;",
        "micro" => "&micro;",
        "macr" => "&macr;",
        "deg" => "&deg;",
        "prime" => "&prime;",
        "Prime" => "&Prime;",
        "infin" => "&infin;",
        "infty" => "&infin;",
        "prop" => "&prop;",
        "propto" => "&prop;",
        "not" => "&not;",
        "neg" => "&not;",
        "land" => "&and;",
        "wedge" => "&and;",
        "lor" => "&or;",
        "vee" => "&or;",
        "cap" => "&cap;",
        "cup" => "&cup;",
        "smile" => "&smile;",
        "frown" => "&frown;",
        "int" => "&int;",
        "therefore" => "&there4;",
        "there4" => "&there4;",
        "because" => "&because;",
        "sim" => "&sim;",
        "cong" => "&cong;",
        "simeq" => "&cong;" ,
        "asymp" => "&asymp;",
        "approx" => "&asymp;",
        "ne" => "&ne;",
        "neq" => "&ne;",
        "equiv" => "&equiv;",

        "triangleq" => "&triangleq;",
        "le" => "&le;",
        "leq" => "&le;",
        "ge" => "&ge;",
        "geq" => "&ge;",
        "lessgtr" => "&lessgtr;",
        "lesseqgtr" => "&lesseqgtr;",
        "ll" => "&Lt;",
        "Ll" => "&Ll;",
        "lll" => "&Ll;",
        "gg" => "&Gt;",
        "Gg" => "&Gg;",
        "ggg" => "&Gg;",
        "prec" => "&pr;",
        "preceq" => "&prcue;",
        "preccurlyeq" => "&prcue;",
        "succ" => "&sc;",
        "succeq" => "&sccue;",
        "succcurlyeq" => "&sccue;",
        "sub" => "&sub;",
        "subset" => "&sub;",
        "sup" => "&sup;",
        "supset" => "&sup;",
        "nsub" => "&nsub;",
        "sube" => "&sube;",
        "nsup" => "&nsup;",
        "supe" => "&supe;",
        "setminus" => "&setminus;",
        "forall" => "&forall;",
        "exist" => "&exist;",
        "exists" => "&exist;",
        "nexist" => "&exist;",
        "nexists" => "&exist;",
        "empty" => "&empty;",
        "emptyset" => "&empty;",
        "isin" => "&isin;",
        "in" => "&isin;",
        "notin" => "&notin;",
        "ni" => "&ni;",
        "nabla" => "&nabla;",
        "ang" => "&ang;",
        "angle" => "&ang;",
        "perp" => "&perp;",
        "parallel" => "&parallel;",
        "sdot" => "&sdot;",
        "cdot" => "&sdot;",
        "lceil" => "&lceil;",
        "rceil" => "&rceil;",
        "lfloor" => "&lfloor;",
        "rfloor" => "&rfloor;",
        "lang" => "&lang;",
        "rang" => "&rang;",
        "langle" => "&lang;",
        "rangle" => "&rang;",
        "hbar" => "&hbar;",
        "mho" => "&mho;",

        // ** Arrows"
        "larr" => "&larr;",
        "leftarrow" => "&larr;" ,
        "gets" => "&larr;" ,
        "lArr" => "&lArr;",
        "Leftarrow" => "&lArr;",
        "uarr" => "&uarr;",
        "uparrow" => "&uarr;",
        "uArr" => "&uArr;",
        "Uparrow" => "&uArr;",
        "rarr" => "&rarr;",
        "to" => "&rarr;",
        "rightarrow" => "&rarr;" ,
        "rArr" => "&rArr;",
        "Rightarrow" => "&rArr;",
        "darr" => "&darr;",
        "downarrow" => "&darr;",
        "dArr" => "&dArr;",
        "Downarrow" => "&dArr;",
        "harr" => "&harr;",
        "leftrightarrow" => "&harr;" ,
        "hArr" => "&hArr;",
        "Leftrightarrow" => "&hArr;",
        "crarr" => "&crarr;",
        "hookleftarrow" => "&crarr;" ,

        // ** Function names"
        "arccos" => "arccos",
        "arcsin" => "arcsin",
        "arctan" => "arctan",
        "arg" => "arg",
        "cos" => "cos",
        "cosh" => "cosh",
        "cot" => "cot",
        "coth" => "coth",
        "csc" => "csc",
        "det" => "det",
        "dim" => "dim",
        "exp" => "exp",
        "gcd" => "gcd",
        "hom" => "hom",
        "inf" => "inf",
        "ker" => "ker",
        "lg" => "lg",
        "lim" => "lim",
        "liminf" => "liminf",
        "limsup" => "limsup",
        "ln" => "ln",
        "log" => "log",
        "max" => "max",
        "min" => "min",
        "Pr" => "Pr",
        "sec" => "sec",
        "sin" => "sin",
        "sinh" => "sinh",
        "tan" => "tan",
        "tanh" => "tanh",

        // ** Signs & Symbols"
        "bull" => "&bull;",
        "bullet" => "&bull;",
        "star" => "*",
        "lowast" => "&lowast;",
        "ast" => "&lowast;",
        "odot" => "o",
        "oplus" => "&oplus;",
        "otimes" => "&otimes;",
        "check" => "&checkmark;",
        "checkmark" => "&check;",

        // ** Miscellaneous seldom used,"
        "ordf" => "&ordf;",
        "ordm" => "&ordm;",
        "cedil" => "&cedil;",
        "oline" => "&oline;",
        "uml" => "&uml;",
        "zwnj" => "&zwnj;",
        "zwj" => "&zwj;",
        "lrm" => "&lrm;",
        "rlm" => "&rlm;",

        // ** Smilies"
        "smiley" => "&#9786;",
        "blacksmile" => "&#9787;",
        "sad" => "&#9785;",
        "frowny" => "&#9785;",

        // ** Suits"
        "clubs" => "&clubs;",
        "clubsuit" => "&clubs;",
        "spades" => "&spades;",
        "spadesuit" => "&spades;",
        "hearts" => "&hearts;",
        "heartsuit" => "&heartsuit;",
        "diams" => "&diams;",
        "diamondsuit" => "&diams;",
        "diamond" => "&diamond;",
        "Diamond" => "&diamond;",
        "loz" => "&loz;",

    // spaces
    "_ " => "&ensp;",
    "_  " => "&ensp;&ensp;",
    "_   " => "&ensp;&ensp;&ensp;",
    "_    " => "&ensp;&ensp;&ensp;&ensp;",
    "_     " => "&ensp;&ensp;&ensp;&ensp;&ensp;",
    "_      " => "&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;",
    "_       " => "&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;",
    "_        " => "&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;",
    "_         " => "&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;",
    "_          " => "&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;",
    "_           " => "&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;",
    "_            " => "&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;",
    "_             " => "&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;",
    "_              " => "&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;",
    "_               " => "&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;",
    "_                " => "&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;",
    "_                 " => "&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;",
    "_                  " => "&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;",
    "_                   " => "&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;",
    "_                    " => "&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;",


};

pub(crate) static ENTITYNAME_SET: phf::Set<&'static str> = phf_set! {
        // * letters
        // ** latin
        "Agrave",
        "agrave",
        "Aacute",
        "aacute",
        "Acirc",
        "acirc",
        "Amacr",
        "amacr",
        "Atilde",
        "atilde",
        "Auml",
        "auml",
        "Aring",
        "AA",
        "aring",
        "AElig",
        "aelig",
        "Ccedil",
        "ccedil",
        "Egrave",
        "egrave",
        "Eacute",
        "eacute",
        "Ecirc",
        "ecirc",
        "Euml",
        "euml",
        "Igrave",
        "igrave",
        "Iacute",
        "iacute",
        "Idot",
        "inodot",
        "Icirc",
        "icirc",
        "Iuml",
        "iuml",
        "Ntilde",
        "ntilde",
        "Ograve",
        "ograve",
        "Oacute",
        "oacute",
        "Ocirc",
        "ocirc",
        "Otilde",
        "otilde",
        "Ouml",
        "ouml",
        "Oslash",
        "oslash",
        "OElig",
        "oelig",
        "Scaron",
        "scaron",
        "szlig",
        "Ugrave",
        "ugrave",
        "Uacute",
        "uacute",
        "Ucirc",
        "ucirc",
        "Uuml",
        "uuml",
        "Yacute",
        "yacute",
        "Yuml",
        "yuml",

        // ** Latin special face,"
        "fnof",
        "real",
        "image",
        "weierp",
        "ell",
        "imath",
        "jmath",

        // ** Greek"
        "Alpha",
        "alpha",
        "Beta",
        "beta",
        "Gamma",
        "gamma",
        "Delta",
        "delta",
        "Epsilon",
        "epsilon",
        "varepsilon",
        "Zeta",
        "zeta",
        "Eta",
        "eta",
        "Theta",
        "theta",
        "thetasym",
        "vartheta",
        "Iota",
        "iota",
        "Kappa",
        "kappa",
        "Lambda",
        "lambda",
        "Mu",
        "mu",
        "nu",
        "Nu",
        "Xi",
        "xi",
        "Omicron",
        "omicron",
        "Pi",
        "pi",
        "Rho",
        "rho",
        "Sigma",
        "sigma",
        "sigmaf",
        "varsigma",
        "Tau",
        "Upsilon",
        "upsih",
        "upsilon",
        "Phi",
        "phi",
        "varphi",
        "Chi",
        "chi",
        "acutex",
        "Psi",
        "psi",
        "tau",
        "Omega",
        "omega",
        "piv",
        "varpi",
        "partial",

        // ** Hebrew"
        "alefsym",
        "aleph",
        "gimel",
        "beth",
        "dalet",

        // ** Icelandic"
        "ETH",
        "eth",
        "THORN",
        "thorn",

        // * Punctuation"
        // ** Dots and Marks"
        "dots",
        "cdots",
        "hellip",
        "middot",
        "iexcl",
        "iquest",

        // ** Dash-like"
        "shy",
        "ndash",
        "mdash",

        // ** Quotations"
        "quot",
        "acute",
        "ldquo",
        "rdquo",
        "bdquo",
        "lsquo",
        "rsquo",
        "sbquo",
        "laquo",
        "raquo",
        "lsaquo",
        "rsaquo",

        // * Other"
        // ** Misc. often used"
        "circ",
        "vert",
        "vbar",
        "brvbar",
        "S",
        "sect",
        "P",
        "para",
        "amp",
        "lt",
        "gt",
        "tilde",
        "slash",
        "plus",
        "under",
        "equal",
        "asciicirc",
        "dagger",
        "dag",
        "Dagger",
        "ddag",

        // ** Whitespace"
        "nbsp",
        "ensp",
        "emsp",
        "thinsp",

        // ** Currency"
        "curren",
        "cent",
        "pound",
        "yen",
        "euro",
        "EUR",
        "dollar",
        "USD",

        // ** Property Marks"
        "copy",
        "reg",
        "trade",

        // ** Science et al."
        "minus",
        "pm",
        "plusmn",
        "times",
        "frasl",
        "colon",
        "div",
        "frac12",
        "frac14",
        "frac34",
        "permil",
        "sup1",
        "sup2",
        "sup3",
        "radic",
        "sum",
        "prod",
        "micro",
        "macr",
        "deg",
        "prime",
        "Prime",
        "infin",
        "infty",
        "prop",
        "propto",
        "not",
        "neg",
        "land",
        "wedge",
        "lor",
        "vee",
        "cap",
        "cup",
        "smile",
        "frown",
        "int",
        "therefore",
        "there4",
        "because",
        "sim",
        "cong",
        "simeq",
        "asymp",
        "approx",
        "ne",
        "neq",
        "equiv",

        "triangleq",
        "le",
        "leq",
        "ge",
        "geq",
        "lessgtr",
        "lesseqgtr",
        "ll",
        "Ll",
        "lll",
        "gg",
        "Gg",
        "ggg",
        "prec",
        "preceq",
        "preccurlyeq",
        "succ",
        "succeq",
        "succcurlyeq",
        "sub",
        "subset",
        "sup",
        "supset",
        "nsub",
        "sube",
        "nsup",
        "supe",
        "setminus",
        "forall",
        "exist",
        "exists",
        "nexist",
        "nexists",
        "empty",
        "emptyset",
        "isin",
        "in",
        "notin",
        "ni",
        "nabla",
        "ang",
        "angle",
        "perp",
        "parallel",
        "sdot",
        "cdot",
        "lceil",
        "rceil",
        "lfloor",
        "rfloor",
        "lang",
        "rang",
        "langle",
        "rangle",
        "hbar",
        "mho",

        // ** Arrows"
        "larr",
        "leftarrow",
        "gets",
        "lArr",
        "Leftarrow",
        "uarr",
        "uparrow",
        "uArr",
        "Uparrow",
        "rarr",
        "to",
        "rightarrow",
        "rArr",
        "Rightarrow",
        "darr",
        "downarrow",
        "dArr",
        "Downarrow",
        "harr",
        "leftrightarrow",
        "hArr",
        "Leftrightarrow",
        "crarr",
        "hookleftarrow",

        // ** Function names"
        "arccos",
        "arcsin",
        "arctan",
        "arg",
        "cos",
        "cosh",
        "cot",
        "coth",
        "csc",
        "det",
        "dim",
        "exp",
        "gcd",
        "hom",
        "inf",
        "ker",
        "lg",
        "lim",
        "liminf",
        "limsup",
        "ln",
        "log",
        "max",
        "min",
        "Pr",
        "sec",
        "sin",
        "sinh",
        "tan",
        "tanh",

        // ** Signs & Symbols"
        "bull",
        "bullet",
        "star",
        "lowast",
        "ast",
        "odot",
        "oplus",
        "otimes",
        "check",
        "checkmark",

        // ** Miscellaneous seldom used,"
        "ordf",
        "ordm",
        "cedil",
        "oline",
        "uml",
        "zwnj",
        "zwj",
        "lrm",
        "rlm",

        // ** Smilies"
        "smiley",
        "blacksmile",
        "sad",
        "frowny",

        // ** Suits"
        "clubs",
        "clubsuit",
        "spades",
        "spadesuit",
        "hearts",
        "heartsuit",
        "diams",
        "diamondsuit",
        "diamond",
        "Diamond",
        "loz",
};
