name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  fmt-clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - run: rustup --version        
      - run: cargo fmt --all -- --check
      # - run: cargo clippy -- -D warnings
        
  test:
    needs: fmt-clippy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
    - uses: Swatinem/rust-cache@v2
    - run: cargo test --verbose

  bench:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
    - uses: Swatinem/rust-cache@v2
    - run: cargo bench

  build:
    needs: test
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
            bin: windancer
          - target: x86_64-pc-windows-msvc
            os: windows-latest
            bin: windancer.exe
          # - target: x86_64-apple-darwin
          #   os: macos-latest
          #   bin: windancer
          # - target: aarch64-apple-darwin
          #   os: macos-latest
          #   bin: windancer
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
    - run: rustup --version
    - uses: Swatinem/rust-cache@v2
    - name: Build
      run: cargo build -r --target ${{ matrix.target }}
    - name: Archive Release (Linux)
      if: runner.os == 'Linux'
      run: tar -czf windancer-${{ matrix.target }}.tar.gz -C target/${{ matrix.target }}/release ${{ matrix.bin }}
    - name: Archive Release (Windows)
      if: runner.os == 'Windows'
      shell: pwsh
      run: Compress-Archive -Path target/${{ matrix.target }}/release/${{ matrix.bin }} -DestinationPath windancer-${{ matrix.target }}.zip
    - name: Archive Release (macOS)
      if: runner.os == 'macOS'
      run: tar -czf windancer-${{ matrix.target }}.tar.gz -C target/${{ matrix.target }}/release ${{ matrix.bin }}
    - name: Upload Final Bundle
      uses: actions/upload-artifact@v4
      with:
        name: release-${{ matrix.target }}
        path: windancer-${{ matrix.target }}.*

  publish:
    needs: [build]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: release-*
          merge-multiple: true
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.inputs.release_version || github.ref_name }}
          name: Release ${{ github.event.inputs.release_version || github.ref_name }}
          draft: false
          prerelease: false
          generate_release_notes: true
          files: |
            windancer-*.tar.gz
            windancer-*.zip

